FROM registry.gitlab.com/artemklevtsov/r-alpine/release:latest

MAINTAINER Artem Klevtsov a.a.klevtsov@gmail.com

ARG R_CRAN_PKG
ARG R_GITHUB_PKG
ARG R_GITLBAB_PKG
ARG R_BITBUCKET_PKG
ARG APK_PKG

RUN apk add ${APK_PKG} && \
    Rscript -e "install.packages('remotes')" && \
    test ! -z "${R_GITHUB_PKG}" && Rscript -e "remotes::install_github(commandArgs(TRUE))" ${R_GITHUB_PKG} || true && \
    test ! -z "${R_GITLBAB_PKG}" && Rscript -e "remotes::install_gitlab(commandArgs(TRUE))" ${R_GITLBAB_PKG} || true && \ 
    test ! -z "${R_BITBUCKET_PKG}" && Rscript -e "remotes::install_bitbucket(commandArgs(TRUE))" ${R_BITBUCKET_PKG} || true && \ 
    test ! -z "${R_CRAN_PKG}" && Rscript -e "remotes::install_cran(commandArgs(TRUE))" ${R_CRAN_PKG} || true
